### ISSUE TITLE
More Eigen API functions exposed in haskell? 

### ISSUE THREAD

**Issue by madjestic** [osidorkin/haskell-eigen#11]
Hey Oleg,

I've been following the [eigen utorial](https://eigen.tuxfamily.org/dox/group__TutorialGeometry.html) and it looks like some functions, available in C++, such as `AngleAxis(angle,axis);` are not available in haskell-eigen.  Are you, perhaps, planning to support more functions at some point or could you give some directions on how I could achieve that?  Or, mayby, I misunderstand how to use the library and access such functions, in which case - could you provide some info on that?  

Regards,
Vlad

**Comment by osidorkin** [comment]
Hi Vlad,

Yes, wrappers for geometry are not yet available. Please feel free to contribute!

Thanks,
Oleg

**Comment by osidorkin** [comment]
this package is maintaned by @chessai at https://github.com/chessai/eigen now. this issue is migrated.
