### ISSUE TITLE
Why define IOSparseMatrix instead of MSparseMatrix?

### ISSUE THREAD

**Issue by taktoa** [osidorkin/haskell-eigen#12]
Why is it that `Data.Eigen.SparseMatrix.Mutable` defines `IOSparseMatrix a b` instead of a `MSparseMatrix a b s` that can be used in the `ST` monad? Are the sparse matrix operations exported by Eigen not pure?

**Comment by chessai** [comment]
I am also wondering this.

**Comment by osidorkin** [comment]
this package is maintaned by @chessai at https://github.com/chessai/eigen now. this issue is migrated.

**Comment by taktoa** [comment]
@osidorkin if you happen to remember why you wrote it that way, it would be greatly appreciated if you could explain
