### ISSUE TITLE
Sparse matrix accession

### ISSUE THREAD

**Issue by GregorySchwartz** [osidorkin/haskell-eigen#13]
Is it possible to efficiently get a row, column, or diagonal of a sparse matrix as a sparse vector? Are `map` and `imap` available for sparse matrices and sparse vectors?

**Comment by chessai** [comment]
For the first question: It looks like `eigen` itself does not carry those operations for sparse matrices. Such a change would need to take place in `eigen` itself.

For the second question: I think so. A function called `_map` exists but is not exported from `Data.Eigen.SparseMatrix`, [here](https://github.com/osidorkin/haskell-eigen/blob/0f00b83482e93dc2f376d7fdf8af471153a3fc45/Data/Eigen/SparseMatrix.hs#L399):

```haskell
_map :: I.Elem a b => (a -> a) -> SparseMatrix a b -> SparseMatrix a b
_map f m = fromVector (rows m) (cols m) . VS.map g . toVector $ m where
    g (I.CTriplet r c v) = I.CTriplet r c $ I.cast $ f $ I.cast v
```

I think an 'imap' could exist. It might look like this:

```haskell
_imap :: I.Elem a b => (Int -> Int -> a -> a) -> SparseMatrix a b -> SparseMatrix a b
_imap f m = fromVector rs cs . VS.map g . toVector $ m where
  rs = rows m
  cs = cols m  
  g n (I.CTriplet r c v) = I.CTriplet r c $ I.cast $ f r' c' $ I.cast v where
    (c', r') = divMod n rs
  
```

**Comment by GregorySchwartz** [comment]
I just finished a small module with additional functions with actually includes those.

**Comment by chessai** [comment]
Where is it located?

**Comment by GregorySchwartz** [comment]
It's not public yet, but I can upload it somewhere.

**Comment by chessai** [comment]
Agreed

**Comment by GregorySchwartz** [comment]
Here's a list of what I have so far, would this be better as a separate module or as part of `Data.Eigen.SparseMatrix`?

```
 _map
 _imap
 getRow
 getCol
 getRows
 getCols
 getRowSums
 getColSums
 getSum
 ones
 ident
 diagCol
 diagRow
 fromRows
 fromCols
 squareSubset
```

**Comment by chessai** [comment]
That's up to @osidorkin, but I myself would prefer it to be part of this library. I'm sure if you made a PR he wouldn't be averse to looking over it.

**Comment by GregorySchwartz** [comment]
Also, what about sparse inverse? I'm not familiar with C glue so I'm not much help there.

**Comment by osidorkin** [comment]
this package is maintaned by @chessai at https://github.com/chessai/eigen now. this issue is migrated.
